name:                inference-for-bta
version:             0.1.0.0
github:              "https://github.com/szokolimatyas/Type-Inference-for-BTA"
license:             BSD3
author:              "M치ty치s Szokoli"
maintainer:          ""
copyright:           "2020 M치ty치s Szokoli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/szokolimatyas/Type-Inference-for-BTA/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1
- mtl >= 2.2.2
- parsec
- QuickCheck >= 2.13
- monad-memo
- criterion
- deepseq

library:
  source-dirs: src

executables:
  partial-inference-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fexcess-precision
    - -optc-ffast-math
    - -optc-O3
    dependencies:
    - partial-inference

tests:
  partial-inference-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - partial-inference
